<?php
session_start();
error_reporting(0);
require_once("dbkn.php");
$logPath = "log/kenyasafari/send_payment_request_scke_renew_from_lowbl_".date("Ymd").".txt";
error_log("called url: ".date('Ymd His').": ".$_SERVER['REQUEST_URI']."\n", 3, $logPath);


$lastid = date("ymdHisu");
$msisdn = $_GET['msisdn'];
//error_log("lastid: " . $lastid . "\n", 3, $logPath);
///////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////


 $Query1 = "select  token from tbl_access_token_playme_enscke order by id desc limit 1";
	 $result=mysqli_query($con1,$Query1);
	 while($mis_array=mysqli_fetch_assoc($result)) {			
			$access_token = $mis_array['token'];
		}
	$_SESSION['msisdn'] =$msisdn;	
	//error_log("access_token:" . date('Ymd His') . ": " . $access_token . "\n", 3, $logPath);
	//error_log("Queryt:" . date('Ymd His') . ": " . $Query1 . "\n", 3, $logPath);
	//error_log("sessionmsisdn:" . date('Ymd His') . ": " .$_SESSION['msisdn']. "\n", 3, $logPath);
    if (!mysqli_query($con1, $Query1)) {
        //error_log("Error description:" . date('Ymd His') . ": " . mysqli_error($con1) . "\n", 3, $logPath);
    }



////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://hesdp.safaricom.com:1212/api/v1/charge');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\t\"msisdn\":\"$msisdn\",\n\t\"offerCode\":\"001023834313\",\n\t\"CpId\":\"238\",\n    \"callBackUrl\": \"http://139.59.3.239:8080/Games24/playme/smartfren/kenya\",\n    \"ChargeAmount\": \"15.00\"\n}");

$headers = array();
$headers[] = 'X-Api-Auth-Token: Bearer  '.$access_token.'';
$headers[] = 'Accept-Encoding: application/json';
$headers[] = 'Accept-Language: EN';
$headers[] = 'Content-Type: application/json';
$headers[] = 'X-App: ussd';
$headers[] = 'X-Correlation-Conversation-Id: '.$lastid.'';
$headers[] = 'X-Messageid: '.$lastid.'';
$headers[] = 'X-Source-Division: DIT';
$headers[] = 'X-Source-Countrycode: KE';
$headers[] = 'X-Source-Operator: Safaricom';
$headers[] = 'X-Source-System: web-portal';
$headers[] = 'X-Source-Timestamp: '.$lastid.'';
$headers[] = 'X-Version: 1.0.0';
$headers[] = 'Authorization: Basic ZGV2X3VzZXI6ZGV2X3Bhc3N3b3Jk';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
//error_log(date('Ymd His').": headers =" .$headers."\n", 3, $logPath);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
//echo $result;
error_log(" Response:".date('Ymd His').": " .$result."\n", 3, $logPath);

$data = json_decode($result,false);
$arr = (object) $data;
//echo $arr->requestId;
//echo $arr->responseParam->status;
//echo $arr->responseParam->statusCode;
$status =$arr->responseParam->status;
$statusCode = $arr->responseParam->statusCode;
$description = $arr->responseParam->description;
?>

