<?php
session_start();
error_reporting(0);
require_once("dbkn.php");
$logPath = "log/kenyasafari/send_payment_renew_".date("Ymd").".txt";
error_log("called url: ".date('Ymd His').": ".$_SERVER['REQUEST_URI']."\n", 3, $logPath);


$lastid = date("ymdHisu");
$msisdn = $_GET['msisdn'];
//error_log("lastid: " . $lastid . "\n", 3, $logPath);
///////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////


 $Query1 = "select  token from tbl_access_token_playme_enscke order by id desc limit 1";
	 $result=mysqli_query($con1,$Query1);
	 while($mis_array=mysqli_fetch_assoc($result)) {			
			$access_token = $mis_array['token'];
		}
	$_SESSION['msisdn'] =$msisdn;	
	//error_log("access_token:" . date('Ymd His') . ": " . $access_token . "\n", 3, $logPath);
	//error_log("Queryt:" . date('Ymd His') . ": " . $Query1 . "\n", 3, $logPath);
	//error_log("sessionmsisdn:" . date('Ymd His') . ": " .$_SESSION['msisdn']. "\n", 3, $logPath);
    if (!mysqli_query($con1, $Query1)) {
        //error_log("Error description:" . date('Ymd His') . ": " . mysqli_error($con1) . "\n", 3, $logPath);
    }



////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

/*
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://hesdp.safaricom.com:1212/api/v1/charge');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\t\"msisdn\":\"$msisdn\",\n\t\"offerCode\":\"001023834313\",\n\t\"CpId\":\"238\",\n    \"callBackUrl\": \"http://139.59.3.239:8080/Games24/playme/smartfren/kenya\",\n    \"ChargeAmount\": \"15.00\"\n}");

$headers = array();
$headers[] = 'X-Api-Auth-Token: Bearer  '.$access_token.'';
$headers[] = 'Accept-Encoding: application/json';
$headers[] = 'Accept-Language: EN';
$headers[] = 'Content-Type: application/json';
$headers[] = 'X-App: ussd';
$headers[] = 'X-Correlation-Conversation-Id: '.$lastid.'';
$headers[] = 'X-Messageid: '.$lastid.'';
$headers[] = 'X-Source-Division: DIT';
$headers[] = 'X-Source-Countrycode: KE';
$headers[] = 'X-Source-Operator: Safaricom';
$headers[] = 'X-Source-System: web-portal';
$headers[] = 'X-Source-Timestamp: '.$lastid.'';
$headers[] = 'X-Version: 1.0.0';
$headers[] = 'Authorization: Basic ZGV2X3VzZXI6ZGV2X3Bhc3N3b3Jk';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
//error_log(date('Ymd His').": headers =" .$headers."\n", 3, $logPath);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
//echo $result;
error_log(" msisdn:".date('Ymd His').": " .$msisdn."\n", 3, $logPath);
error_log(" Response:".date('Ymd His').": " .$result."\n", 3, $logPath);

$responseArray = json_decode($result, true);
$description = $responseArray['body']['description'];
error_log(" description:".date('Ymd His').": " .$description."\n", 3, $logPath);




*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/*
$Queryn1 = "select  id from subscriberdoesnotexist_kenyasafaricom_game24 where msisdn = '$msisdn'";
	 $result2=mysqli_query($con1,$Queryn1);
	 while($mis_array=mysqli_fetch_assoc($result2)) {			
			$id = $mis_array['id'];
			error_log("id: " . $id . "\n", 3, $logPath);		
			
		}		
if($description=="Subscription does not exists for the subscriber" && $id == ""){
	$Querydel   = "insert into subscriberdoesnotexist_kenyasafaricom_game24(regdate,lastupdatedate,msisdn)
	values (now(),now(),'$msisdn')";
    error_log("Querydel:" . date('Ymd His') . ": " . $Querydel . "\n", 3, $logPath);
    if (!mysqli_query($con1, $Querydel)) {
        error_log("Error description:" . date('Ymd His') . ": " . mysqli_error($con1) . "\n", 3, $logPath);
    }

}

*/

/////////////////////////////////////////////with new end points /////////////////////////////////////////////////////////////
$ch = curl_init();
//curl_setopt($ch, CURLOPT_URL, 'https://dtsvc.safaricom.com:8480/api/public/SDP/activate');
curl_setopt($ch, CURLOPT_URL, 'https://dsvc.safaricom.com:9480/api/public/SDP/paymentRequest');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"requestId\": \"$lastid\",\n  \"channel\": \"APIGW\",\n  \"operation\": \"ACTIVATE\",\n  \"requestParam\": {\n    \"data\": [\n      {\n        \"name\": \"OfferCode\",\n        \"value\": \"001034001290\"\n      },\n      {\n        \"name\": \"Msisdn\",\n        \"value\": \"$msisdn\"\n      },\n      {\n        \"name\": \"CpId\",\n        \"value\": \"340\"\n      }\n    ]\n  }\n}");
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"requestId\": \"$lastid\",\n  \"channel\": \"APIGW\",\n  \"operation\": \"Payment\",\n  \"requestParam\": {\n    \"data\": [\n      {\n        \"name\": \"OfferCode\",\n        \"value\": \"001023834313\"\n      },\n      {\n        \"name\": \"Msisdn\",\n        \"value\": \"$msisdn\"\n      },\n      {\n        \"name\": \"ChargeAmount\",\n        \"value\": \"15.00\"\n      },\n      {\n        \"name\": \"CpId\",\n        \"value\": \"238\"\n      }\n    ]\n  }\n}");

$headers = array();
$headers[] = 'Accept: */*';
$headers[] = 'Authorization: Basic ZGV2X3VzZXI6ZGV2X3Bhc3N3b3Jk';
//$headers[] = 'Content-Length: 248';
$headers[] = 'Content-Type: application/json';
//$headers[] = 'Sourceaddress:  '.$ip.'';
//$headers[] = 'User-Agent:  '.$UserAgent.'';
$headers[] = 'X-Authorization: Bearer  '.$access_token.'';
$headers[] = 'X-Requested-With: XMLHttpRequest';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

error_log(date('Ymd His').": headers =" .$headers."\n", 3, $logPath);
error_log(date('Ymd His') . ": headers = " . var_export($headers, true) . "\n", 3, $logPath);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

error_log(" ch:".date('Ymd His').": " .$ch."\n", 3, $logPath);
curl_close($ch);


error_log(" Response:".date('Ymd His').": " .$result."\n", 3, $logPath);

$data = json_decode($result,false);
$arr = (object) $data;
//echo $arr->requestId;
//echo $arr->responseParam->status;
//echo $arr->responseParam->statusCode;
$status =$arr->responseParam->status;
$statusCode = $arr->responseParam->statusCode;
$description = $arr->responseParam->description;

echo $description;




///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
?>

