<?php
session_start();
error_reporting(0);
require_once("dbkn.php");
$logPath = "log/kenyasafari/sendcalllbacktoupstream_payment_".date("Ymd").".txt";
error_log("called url: ".date('Ymd His').": ".$_SERVER['REQUEST_URI']."\n", 3, $logPath);

$msisdn = $_GET['msisdn'];
//$Reason = date("Reason");
$lastid = $_GET['lastid'];
////////////////////////////
//$str="enyo@173:TIYH2WLRUO";
//$access_token=base64_encode($str);
//$access_token = str_replace(array("\n", "\r"), '', $access_token);
//error_log(date('Ymd His')." access_token=$access_token\n", 3, $logPath);
////////////////////////////
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//http://www.dot-jo.biz:8/partners-subscription-notification-Staging///
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'http://91.241.94.30:7014/cp/notifications',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
    "msisdn": "'.$msisdn.'",
    "source": "SecureD",
    "trxID":"'.$lastid.'",
    "result": "successful subscription",
    "description": "success"
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json',
    'Accept: application/json'
  ),
));

$response = curl_exec($curl);

$httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);

curl_close($curl);
//echo $response;
//echo $result;
error_log(" Response:".date('Ymd His').": " .$response."\n", 3, $logPath);
error_log(" httpcode:".date('Ymd His').": " .$httpcode."\n", 3, $logPath);

$data = json_decode($response,false);
$arr = (object) $data;
//echo $arr->requestId;
//echo $arr->responseParam->status;
//echo $arr->responseParam->statusCode;
$errorCode =$arr->errorCode;
$errorDesc = $arr->errorDesc;
$dotTransId = $arr->dotTransId;

/*

if($errorCode=="0")
{
	header("Location:directbilling_endotzonggames24.php?lastid=$lastid&msisdn=$msisdn");
	exit;
}else{
	if($description=="")
		{
			$description = $arr->errorDesc;			
			}		
	header("Location:errormessage_endotzonggames24.php?status=$status&statusCode=$statusCode&description=$description");
	exit;
}

*/

?>

